apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-aws-secret
  namespace: {{ .Values.namespace }}
spec:
  provider: aws
  parameters:
    region: {{ .Values.region }}
    objects: | # jmesPath is to parse key-pair values instead of json
      - objectName: {{ .Values.namespace }}/env
        objectType: secretsmanager
        jmesPath:
            - path: environment # object in aws secret
              objectAlias: environment_name # alias to be used as a secret name (objectName below)
  secretObjects: # this will create a secret k8s object with values from above
    - secretName: app-k8s-secret
      type: Opaque
      data:
        - objectName: environment_name
          key: k8s_secret_key_environment_name