apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: app-aws-secrets
  namespace: {{ .Values.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  provider: aws
  parameters:
    region: {{ .Values.region }}
    objects: | # jmesPath is to parse key-pair values instead of json; jmesPath[0].path is the param within aws secret
      - objectName: {{ .Values.namespace }}/env
        objectType: secretsmanager
        jmesPath:
            - path: environment
              objectAlias: environment_name
  secretObjects: # this will create a secret k8s object with values from above
    - secretName: app-k8s-secret
      type: Opaque
      data:
        - key: k8s_secret_key_environment_name # k8s secret's key
          objectName: environment_name # ref to value defined in jmesPath objectAlias