#apiVersion: gateway.k8s.aws/v1beta1
#kind: TargetGroupConfiguration
#metadata:
#  name: custom-tg-config
#  namespace: platform
#  annotations:
#    argocd.argoproj.io/sync-wave: "0"
#spec:
#  targetReference:
#    group: ""
#    kind: Service
#    name: argo-deployment-demo-app-svc-dev
#    namespace: dev
#  defaultConfiguration:
#    targetType: ip