namespace: dev
replicaCount: 1
image:
  repository: 228305238849.dkr.ecr.us-east-1.amazonaws.com/argo-deployment-demo-app
  tag: "0.0.8"
  pullPolicy: IfNotPresent
hostname: dev-app.niks.cloud
region: us-east-1
aws_role_for_k8s_service_account: arn:aws:iam::228305238849:role/argo-deployment-demo-cluster-dev-app-secrets