apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: secrets-store-csi-driver
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-3"
spec:
  project: default

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  source:
    repoURL: https://kubernetes-sigs.github.io/secrets-store-csi-driver/charts
    chart: secrets-store-csi-driver
    targetRevision: 1.6.0
    helm:
      # since we're installing the csi driver separately from csi-driver aws provider
      # we need to set tokenRequests: https://github.com/aws/secrets-store-csi-driver-provider-aws#separate-csi-driver-installation
      values: |
        syncSecret:
          enabled: true
        tokenRequests:
          - audience: "sts.amazonaws.com"
          - audience: "pods.eks.amazonaws.com"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true