clusterName: argo-deployment-demo-cluster
region: us-east-1
vpcId: vpc-083bdd7672d99cf4e # TODO: set the new vpc id here
serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::228305238849:role/alb-ingress-controller-argo-deployment-demo
enableCertManager: false
