clusterName: argo-deployment-demo-cluster
region: us-east-1
vpcId: vpc-0b1ea4df849d131ae # TODO: set the new vpc id here
serviceAccount:
  create: true
  name: aws-load-balancer-controller
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::228305238849:role/alb-ingress-controller-argo-deployment-demo
enableCertManager: false
